// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.timmaffett.google_maps_places_autocomplete_widgets_native

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class NativePrediction (
  val placeId: String,
  val fullText: String,
  val primaryText: String? = null,
  val secondaryText: String? = null,
  val types: List<String>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativePrediction {
      val placeId = pigeonVar_list[0] as String
      val fullText = pigeonVar_list[1] as String
      val primaryText = pigeonVar_list[2] as String?
      val secondaryText = pigeonVar_list[3] as String?
      val types = pigeonVar_list[4] as List<String>?
      return NativePrediction(placeId, fullText, primaryText, secondaryText, types)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      placeId,
      fullText,
      primaryText,
      secondaryText,
      types,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativePrediction) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAddressComponent (
  val types: List<String>,
  val longText: String? = null,
  val shortText: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAddressComponent {
      val types = pigeonVar_list[0] as List<String>
      val longText = pigeonVar_list[1] as String?
      val shortText = pigeonVar_list[2] as String?
      return NativeAddressComponent(types, longText, shortText)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      types,
      longText,
      shortText,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeAddressComponent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativePlaceDetails (
  val name: String? = null,
  val formattedAddress: String? = null,
  val lat: Double? = null,
  val lng: Double? = null,
  val components: List<NativeAddressComponent>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativePlaceDetails {
      val name = pigeonVar_list[0] as String?
      val formattedAddress = pigeonVar_list[1] as String?
      val lat = pigeonVar_list[2] as Double?
      val lng = pigeonVar_list[3] as Double?
      val components = pigeonVar_list[4] as List<NativeAddressComponent>
      return NativePlaceDetails(name, formattedAddress, lat, lng, components)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      formattedAddress,
      lat,
      lng,
      components,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativePlaceDetails) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativePrediction.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAddressComponent.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativePlaceDetails.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativePrediction -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeAddressComponent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativePlaceDetails -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PlacesNativeApi {
  /** Initializes the native Places SDK (New). Safe to call once at startup. */
  fun initialize(apiKey: String, useAppCheck: Boolean, callback: (Result<Unit>) -> Unit)
  /**
   * Session tokens are managed natively: created lazily on the first call,
   * reused until [fetchPlace] consumes them.
   */
  fun fetchPredictions(query: String, includedTypes: List<String>, countryCode: String?, languageCode: String?, callback: (Result<List<NativePrediction>>) -> Unit)
  fun fetchPlace(placeId: String, languageCode: String?, callback: (Result<NativePlaceDetails>) -> Unit)

  companion object {
    /** The codec used by PlacesNativeApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `PlacesNativeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PlacesNativeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.google_maps_places_autocomplete_widgets_native.PlacesNativeApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val apiKeyArg = args[0] as String
            val useAppCheckArg = args[1] as Boolean
            api.initialize(apiKeyArg, useAppCheckArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.google_maps_places_autocomplete_widgets_native.PlacesNativeApi.fetchPredictions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryArg = args[0] as String
            val includedTypesArg = args[1] as List<String>
            val countryCodeArg = args[2] as String?
            val languageCodeArg = args[3] as String?
            api.fetchPredictions(queryArg, includedTypesArg, countryCodeArg, languageCodeArg) { result: Result<List<NativePrediction>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.google_maps_places_autocomplete_widgets_native.PlacesNativeApi.fetchPlace$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val placeIdArg = args[0] as String
            val languageCodeArg = args[1] as String?
            api.fetchPlace(placeIdArg, languageCodeArg) { result: Result<NativePlaceDetails> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
