// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


class NativePrediction {
  NativePrediction({
    required this.placeId,
    required this.fullText,
    this.primaryText,
    this.secondaryText,
    this.types,
  });

  String placeId;

  String fullText;

  String? primaryText;

  String? secondaryText;

  List<String>? types;

  List<Object?> _toList() {
    return <Object?>[
      placeId,
      fullText,
      primaryText,
      secondaryText,
      types,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativePrediction decode(Object result) {
    result as List<Object?>;
    return NativePrediction(
      placeId: result[0]! as String,
      fullText: result[1]! as String,
      primaryText: result[2] as String?,
      secondaryText: result[3] as String?,
      types: (result[4] as List<Object?>?)?.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativePrediction || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class NativeAddressComponent {
  NativeAddressComponent({
    required this.types,
    this.longText,
    this.shortText,
  });

  List<String> types;

  String? longText;

  String? shortText;

  List<Object?> _toList() {
    return <Object?>[
      types,
      longText,
      shortText,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeAddressComponent decode(Object result) {
    result as List<Object?>;
    return NativeAddressComponent(
      types: (result[0] as List<Object?>?)!.cast<String>(),
      longText: result[1] as String?,
      shortText: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAddressComponent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class NativePlaceDetails {
  NativePlaceDetails({
    this.name,
    this.formattedAddress,
    this.lat,
    this.lng,
    required this.components,
  });

  String? name;

  String? formattedAddress;

  double? lat;

  double? lng;

  List<NativeAddressComponent> components;

  List<Object?> _toList() {
    return <Object?>[
      name,
      formattedAddress,
      lat,
      lng,
      components,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativePlaceDetails decode(Object result) {
    result as List<Object?>;
    return NativePlaceDetails(
      name: result[0] as String?,
      formattedAddress: result[1] as String?,
      lat: result[2] as double?,
      lng: result[3] as double?,
      components: (result[4] as List<Object?>?)!.cast<NativeAddressComponent>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativePlaceDetails || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativePrediction) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is NativeAddressComponent) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is NativePlaceDetails) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return NativePrediction.decode(readValue(buffer)!);
      case 130: 
        return NativeAddressComponent.decode(readValue(buffer)!);
      case 131: 
        return NativePlaceDetails.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PlacesNativeApi {
  /// Constructor for [PlacesNativeApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PlacesNativeApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Initializes the native Places SDK (New). Safe to call once at startup.
  Future<void> initialize(String apiKey, bool useAppCheck) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.google_maps_places_autocomplete_widgets_native.PlacesNativeApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[apiKey, useAppCheck]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Session tokens are managed natively: created lazily on the first call,
  /// reused until [fetchPlace] consumes them.
  Future<List<NativePrediction>> fetchPredictions(String query, List<String> includedTypes, String? countryCode, String? languageCode) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.google_maps_places_autocomplete_widgets_native.PlacesNativeApi.fetchPredictions$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[query, includedTypes, countryCode, languageCode]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<NativePrediction>();
    }
  }

  Future<NativePlaceDetails> fetchPlace(String placeId, String? languageCode) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.google_maps_places_autocomplete_widgets_native.PlacesNativeApi.fetchPlace$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[placeId, languageCode]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NativePlaceDetails?)!;
    }
  }
}
