// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct NativePrediction: Hashable {
  var placeId: String
  var fullText: String
  var primaryText: String? = nil
  var secondaryText: String? = nil
  var types: [String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativePrediction? {
    let placeId = pigeonVar_list[0] as! String
    let fullText = pigeonVar_list[1] as! String
    let primaryText: String? = nilOrValue(pigeonVar_list[2])
    let secondaryText: String? = nilOrValue(pigeonVar_list[3])
    let types: [String]? = nilOrValue(pigeonVar_list[4])

    return NativePrediction(
      placeId: placeId,
      fullText: fullText,
      primaryText: primaryText,
      secondaryText: secondaryText,
      types: types
    )
  }
  func toList() -> [Any?] {
    return [
      placeId,
      fullText,
      primaryText,
      secondaryText,
      types,
    ]
  }
  static func == (lhs: NativePrediction, rhs: NativePrediction) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAddressComponent: Hashable {
  var types: [String]
  var longText: String? = nil
  var shortText: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAddressComponent? {
    let types = pigeonVar_list[0] as! [String]
    let longText: String? = nilOrValue(pigeonVar_list[1])
    let shortText: String? = nilOrValue(pigeonVar_list[2])

    return NativeAddressComponent(
      types: types,
      longText: longText,
      shortText: shortText
    )
  }
  func toList() -> [Any?] {
    return [
      types,
      longText,
      shortText,
    ]
  }
  static func == (lhs: NativeAddressComponent, rhs: NativeAddressComponent) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativePlaceDetails: Hashable {
  var name: String? = nil
  var formattedAddress: String? = nil
  var lat: Double? = nil
  var lng: Double? = nil
  var components: [NativeAddressComponent]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativePlaceDetails? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let formattedAddress: String? = nilOrValue(pigeonVar_list[1])
    let lat: Double? = nilOrValue(pigeonVar_list[2])
    let lng: Double? = nilOrValue(pigeonVar_list[3])
    let components = pigeonVar_list[4] as! [NativeAddressComponent]

    return NativePlaceDetails(
      name: name,
      formattedAddress: formattedAddress,
      lat: lat,
      lng: lng,
      components: components
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      formattedAddress,
      lat,
      lng,
      components,
    ]
  }
  static func == (lhs: NativePlaceDetails, rhs: NativePlaceDetails) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativePrediction.fromList(self.readValue() as! [Any?])
    case 130:
      return NativeAddressComponent.fromList(self.readValue() as! [Any?])
    case 131:
      return NativePlaceDetails.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativePrediction {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAddressComponent {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativePlaceDetails {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PlacesNativeApi {
  /// Initializes the native Places SDK (New). Safe to call once at startup.
  func initialize(apiKey: String, useAppCheck: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  /// Session tokens are managed natively: created lazily on the first call,
  /// reused until [fetchPlace] consumes them.
  func fetchPredictions(query: String, includedTypes: [String], countryCode: String?, languageCode: String?, completion: @escaping (Result<[NativePrediction], Error>) -> Void)
  func fetchPlace(placeId: String, languageCode: String?, completion: @escaping (Result<NativePlaceDetails, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PlacesNativeApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `PlacesNativeApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PlacesNativeApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Initializes the native Places SDK (New). Safe to call once at startup.
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.google_maps_places_autocomplete_widgets_native.PlacesNativeApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let apiKeyArg = args[0] as! String
        let useAppCheckArg = args[1] as! Bool
        api.initialize(apiKey: apiKeyArg, useAppCheck: useAppCheckArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Session tokens are managed natively: created lazily on the first call,
    /// reused until [fetchPlace] consumes them.
    let fetchPredictionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.google_maps_places_autocomplete_widgets_native.PlacesNativeApi.fetchPredictions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchPredictionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let queryArg = args[0] as! String
        let includedTypesArg = args[1] as! [String]
        let countryCodeArg: String? = nilOrValue(args[2])
        let languageCodeArg: String? = nilOrValue(args[3])
        api.fetchPredictions(query: queryArg, includedTypes: includedTypesArg, countryCode: countryCodeArg, languageCode: languageCodeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      fetchPredictionsChannel.setMessageHandler(nil)
    }
    let fetchPlaceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.google_maps_places_autocomplete_widgets_native.PlacesNativeApi.fetchPlace\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchPlaceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        let languageCodeArg: String? = nilOrValue(args[1])
        api.fetchPlace(placeId: placeIdArg, languageCode: languageCodeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      fetchPlaceChannel.setMessageHandler(nil)
    }
  }
}
